# Generated by Django 4.1.7 on 2023-03-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='languages',
        ),
    ]
