# Generated by Django 4.1.7 on 2023-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_remove_country_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.TextField(default='Языки', max_length=1000),
        ),
    ]
