# Generated by Django 4.2.1 on 2023-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_language_remove_country_languages_country_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(related_name='countries_that_use', to='MainApp.language'),
        ),
    ]
